# Generated by Django 5.2.7 on 2026-02-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('experience', 'Experience'), ('degree', 'Degree'), ('location', 'Based In'), ('email', 'Email'), ('phone', 'Phone'), ('availability', 'Availability')], max_length=20)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range', models.CharField(max_length=50)),
                ('degree_level', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('achievement', models.CharField(blank=True, max_length=200)),
                ('achievement_icon', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('skills_tags', models.CharField(blank=True, max_length=300)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('creative', 'Creative'), ('digital', 'Digital'), ('strategy', 'Strategy'), ('development', 'Development')], max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('year', models.CharField(blank=True, max_length=10)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(help_text='Comma-separated list used by the typed animation', max_length=200)),
                ('hero_text', models.TextField(blank=True)),
                ('about_title', models.CharField(default='About Me', max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('projects_count', models.PositiveIntegerField(default=0)),
                ('years_experience', models.CharField(blank=True, max_length=50)),
                ('awards_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('background', models.ImageField(blank=True, upload_to='backgrounds/')),
                ('cv', models.FileField(blank=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField()),
            ],
        ),
    ]
