# Generated by Django 5.2.7 on 2026-02-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(choices=[('solo', 'Solo'), ('band', 'Band')], max_length=50),
        ),
    ]
