# Generated by Django 5.2.7 on 2026-03-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolioitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Choose a parent service if this is a sub‑service', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='portfolio.service'),
        ),
    ]
