# Generated by Django 5.2.7 on 2026-03-02 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_customerservices_tech_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservices',
            name='customer_services',
            field=models.ForeignKey(default=1, help_text='Select the service this customer service is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='customer_services', to='portfolio.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech_tools',
            name='tech_tools',
            field=models.ForeignKey(default=1, help_text='Select the service this tool is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='tech_tools', to='portfolio.service'),
            preserve_default=False,
        ),
    ]
