# Generated by Django 5.2.7 on 2026-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_customerservices_customer_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_time',
            field=models.CharField(blank=True, help_text="e.g., '4-6 weeks delivery'", max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='revisions',
            field=models.CharField(blank=True, help_text="e.g., 'Unlimited revisions'", max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='starting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='support_duration',
            field=models.CharField(blank=True, help_text="e.g., '60 days support'", max_length=100),
        ),
    ]
